/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import Modelos.Regiones;
import Modelos.Departamentos;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Gerardo
 */
public class departamentos extends javax.swing.JPanel {

    /**
     * Creates new form Departamentos
     */
    public departamentos() {
        initComponents();
        listaDepartamentos.add(new Departamentos("M", "Metropolitana",1,"Guatemala"));
        listaDepartamentos.add(new Departamentos("NT", "Norte",2,"Peten"));
        listaDepartamentos.add(new Departamentos("NO", "Nororiente",3,"Quetzaltenango"));

        ListaRegiones();
       
        
    }
    Regiones temp = new Regiones();
    regiones regio = new regiones();
    Departamentos Dep = new Departamentos();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codigo = new javax.swing.JComboBox<>();
        nombre = new javax.swing.JTextField();
        nombreRegion = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        labelCodigoDep = new javax.swing.JLabel();
        codigoDep = new javax.swing.JTextField();
        editar = new javax.swing.JButton();
        mostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarRegiones = new javax.swing.JTextPane();

        jPanel1.setBackground(new java.awt.Color(4, 80, 113));

        jLabel1.setText("Codigo de Region");

        jLabel2.setText("Departamento");

        jLabel3.setText("Nombre de Region");

        codigo.setName(""); // NOI18N
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });

        nombreRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreRegionActionPerformed(evt);
            }
        });

        guardar.setText("Guardar Departamento");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        jLabel5.setText("Departamentos");

        labelCodigoDep.setText("Codigo Departamento");

        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        mostrar.setText("Mostrar");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        mostrarRegiones.setContentType("text/html"); // NOI18N
        jScrollPane1.setViewportView(mostrarRegiones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(codigo, javax.swing.GroupLayout.Alignment.LEADING, 0, 135, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(nombreRegion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(labelCodigoDep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(codigoDep, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editar)
                        .addGap(18, 18, 18)
                        .addComponent(mostrar)
                        .addGap(95, 95, 95))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(332, 332, 332))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelCodigoDep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(codigoDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guardar)
                            .addComponent(editar)
                            .addComponent(mostrar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        editar.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreRegionActionPerformed
      rellenarCampos(); 
    }//GEN-LAST:event_nombreRegionActionPerformed

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        rellenarCampos();
    }//GEN-LAST:event_codigoActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
      try{
        String codReg = codigo.getSelectedItem().toString();
        String nomReg= nombreRegion.getText();
        String codDep= codigoDep.getText();
        String nomDep = nombre.getText();
        
        if(!(codReg.equals("") || nomReg.equals("") || codDep.equals("") || nomDep.equals(""))){
            int codDepI = Integer.parseInt(codDep);
            
           
                listaDepartamentos.add(new Departamentos(codReg, nomReg, codDepI, nomDep ));
                System.out.println("Codigo Reg: "+codReg +" nombre reg: " + nomReg+" Codigo Departamento: " + codDepI +" nombre Departamento: " + nomDep);
                JOptionPane.showConfirmDialog(this, "Se ha agregado el deparatamento: " + nomDep, "Confirmar acción", JOptionPane.DEFAULT_OPTION);
                reseteoCampos();
            
        }else{            
            System.out.println("Ingrese todos los datos");
            JOptionPane.showConfirmDialog(this, "Ingrese todos los datos", "Confirmar acción", JOptionPane.DEFAULT_OPTION);

        }
        }catch(java.lang.NumberFormatException v ){
               codigoDep.setText("");
               labelCodigoDep.setForeground(Color.red);               
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        
        try{
        String codReg = codigo.getSelectedItem().toString();
        String nomReg= nombreRegion.getText();
        String codDep= codigoDep.getText();
        String nomDep = nombre.getText();
        
        if(!(codReg.equals("") || nomReg.equals("") || codDep.equals("") || nomDep.equals(""))){
            int codDepI = Integer.parseInt(codDep);
            
                int i = obtenerPosicionDep(codDepI);
                listaDepartamentos.set(i,new Departamentos(codReg, nomReg, codDepI, nomDep ));
                System.out.println("Codigo Reg: "+codReg +" nombre reg: " + nomReg+" Codigo Departamento: " + codDepI +" nombre Departamento: " + nomDep);
                JOptionPane.showConfirmDialog(this, "Se ha editado el deparatamento: " + nomDep, "Confirmar acción", JOptionPane.DEFAULT_OPTION);

                reseteoCampos();
            
        }else{            
            System.out.println("Ingrese todos los datos");
            JOptionPane.showConfirmDialog(this, "Ingrese todos los datos", "Confirmar acción", JOptionPane.DEFAULT_OPTION);

        }
        }catch(Exception  v ){
               codigoDep.setText("");
               codigoDep.setText("");
               labelCodigoDep.setForeground(Color.red);                 
        }
    }//GEN-LAST:event_editarActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
     String cadenaDep="<html><head></head><body><table><tr><th>Codigo Reg</th><th>Nombre Reg</th><th>Codigo Reg</th><th>Nombre departamento</th><tr>";  
        for(int i=0; i<listaDepartamentos.size();i++){
            
            Dep = listaDepartamentos.get(i);            
            cadenaDep = cadenaDep+"<tr><td>"+Dep.getCodigoReg()+"</td><td>"+Dep.getRegion()+"</td>"+"<td>"+Dep.getCodigoDep()+"</td>"+"<td>"+Dep.getNombre()+"</td></tr>";            
        }
        
        cadenaDep=cadenaDep+"</table></body></html>";
        
        mostrarRegiones.setText(cadenaDep);
    }//GEN-LAST:event_mostrarActionPerformed

   
    
    /*
        Funciones
    */
    
    ArrayList <Departamentos> listaDepartamentos = new ArrayList<Departamentos>();
    
    public ArrayList<Departamentos> getListaDepartamentos() {
        return listaDepartamentos;
    }
    
    public void reseteoCampos(){
        codigo.setSelectedItem("");
        nombreRegion.setText("");
        codigoDep.setText("");
        nombre.setText("");
    }
    
    public void ListaRegiones(){
    for(int i= 0; i< regio.getListaRegiones().size(); i++){
        temp = regio.getListaRegiones().get(i);
        codigo.addItem(temp.getCodigo());
        }
}
    
    
    public int obtenerPosicionReg(String cod){
    for(int i = 0; i <  regio.getListaRegiones().size(); i++){
        Regiones r = regio.getListaRegiones().get(i);
                if(cod.equalsIgnoreCase(r.getCodigo())){
                    return i;
    }            
    }
   return -1;
}
   
    public int obtenerPosicionDep(int cod){
    for(int i = 0; i <  listaDepartamentos.size(); i++){
        Departamentos d = listaDepartamentos.get(i);
                if(cod == d.getCodigoDep()){
                    return i;
    }
    }
    return -1;
}
    
    
    public void rellenarCampos(){
      String cod = codigo.getSelectedItem().toString();
      temp = regio.getListaRegiones().get(obtenerPosicionReg(cod));
      
      nombreRegion.setText(temp.getNombre());
      nombreRegion.setEditable(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> codigo;
    private javax.swing.JTextField codigoDep;
    private javax.swing.JButton editar;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCodigoDep;
    private javax.swing.JButton mostrar;
    private javax.swing.JTextPane mostrarRegiones;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombreRegion;
    // End of variables declaration//GEN-END:variables
}
