/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import Modelos.Tarjetas;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Gerardo
 */
public class tarjeta extends javax.swing.JPanel {

    /**
     * Creates new form tarjeta
     */
    public tarjeta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numeroTarjeta = new javax.swing.JTextField();
        nombreTarjeta = new javax.swing.JTextField();
        fechaExp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        numerolabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTarjetas = new javax.swing.JTextPane();
        agregar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        mostrar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        correolabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(4, 80, 113));

        jLabel1.setText("Nombre Tarjeta");

        numerolabel.setText("Numero Tarjeta");

        jLabel3.setText("Fecha Expiracion");

        txtTarjetas.setContentType("text/html"); // NOI18N
        jScrollPane1.setViewportView(txtTarjetas);

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        mostrar.setText("Mostrar");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        jLabel4.setText("Tarjetas");

        correolabel.setText("Correo del usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(nombreTarjeta)
                        .addComponent(numerolabel)
                        .addComponent(numeroTarjeta)
                        .addComponent(fechaExp)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addComponent(correo))
                    .addComponent(correolabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(120, 120, 120))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(7, 7, 7)
                        .addComponent(nombreTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numerolabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fechaExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregar)
                            .addComponent(editar)
                            .addComponent(eliminar))
                        .addGap(18, 18, 18)
                        .addComponent(mostrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(correolabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        agregar.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    Tarjetas tar = new Tarjetas();
    
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
       try{
        String cod = correo.getText();
        String nom= nombreTarjeta.getText();
        String num= numeroTarjeta.getText();
        String fecha = fechaExp.getText();
        
        if(!(cod.equals("") || nom.equals("") || num.equals("") || fecha.equals("")||  num.length()<4)){
           
                listaTarjetas.add(new Tarjetas(cod, nom, num, fecha ));
                System.out.println("Cod: "+cod +" nombre Tarjeta: " + nom+" numero Tarjeta: " + num +" Fecha Exp: " + fecha);
                JOptionPane.showConfirmDialog(this, "Se ingreso la tarjeta: " + num, "Confirmar acción", JOptionPane.DEFAULT_OPTION);

                
                reseteoCampos();
            
        }else{            
            JOptionPane.showConfirmDialog(this, "Ingrese todos los datos", "Confirmar acción", JOptionPane.DEFAULT_OPTION);

        }
        }catch(Exception  e ){
               numerolabel.setForeground(Color.red);
        }                                     

    }//GEN-LAST:event_agregarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        try{
        String cod = correo.getText();
        String nom= nombreTarjeta.getText();
        String num= numeroTarjeta.getText();
        String fecha = fechaExp.getText();
        
        if(!(cod.equals("") || nom.equals("") || num.equals("") || fecha.equals("")|| num.length()<4)){
           
                int i = obtenerPosicion(num);
                listaTarjetas.set(i,new Tarjetas(cod, nom, num, fecha ));
                System.out.println("Cod: "+cod +" nombre Tarjeta: " + nom+" numero Tarjeta: " + num +" Fecha Exp: " + fecha);
                JOptionPane.showConfirmDialog(this, "Se modifico la tarjeta: " + num, "Confirmar acción", JOptionPane.DEFAULT_OPTION);

                reseteoCampos();
            
        }else{            
            System.out.println("Ingrese todos los datos");
            JOptionPane.showConfirmDialog(this, "Ingrese todos los datos", "Confirmar acción", JOptionPane.DEFAULT_OPTION);

        }
        }catch(Exception  e ){
               numerolabel.setForeground(Color.red);
        }  
    }//GEN-LAST:event_editarActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        try{
        String cadenaTarjeta="<html><head></head><body><table><tr><th>Nombre Tarjeta</th><th>Numero Tarjeta</th><th>Fecha Exp</th><th>Correo</th></tr>";  
        for(int i=0; i<listaTarjetas.size();i++){
            
            tar = listaTarjetas.get(i);
            if(correo.getText().equals("")){
             JOptionPane.showConfirmDialog(this, "Falta el correo", "Confirmar acción", JOptionPane.DEFAULT_OPTION);
             correolabel.setForeground(Color.red);

            }else{
            if(tar.getCorreo().equals(correo.getText())){
                    cadenaTarjeta = cadenaTarjeta+"<tr><td>"+ tar.getNombreTarjeta()+"</td><td>"+ocultarNumeros(tar.getNumeroTarjeta())+"</td>"+"<td>"+tar.getFechaVencimiento()+"<td>"+tar.getCorreo()+"</td></tr>";
            }else{
                System.out.println("No es del usuario");
            }
            }
            
        }
        
        cadenaTarjeta=cadenaTarjeta+"</table></body></html>";
        
        txtTarjetas.setText(cadenaTarjeta);
        }catch(Exception e){
            numerolabel.setForeground(Color.red);

        } 
        
    }//GEN-LAST:event_mostrarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        try{ 
        String num= numeroTarjeta.getText();

        listaTarjetas.remove(obtenerPosicion(num));
        JOptionPane.showConfirmDialog(this, "Se elimino la tarjeta", "Confirmar acción", JOptionPane.DEFAULT_OPTION);

                }catch(Exception e){
                  numerolabel.setForeground(Color.red);
                   JOptionPane.showConfirmDialog(this, "Se necesita numero de tarjeta para eliminar", "Confirmar acción", JOptionPane.DEFAULT_OPTION);

                }
    }//GEN-LAST:event_eliminarActionPerformed


   ArrayList <Tarjetas> listaTarjetas = new ArrayList <Tarjetas>();
   
   public ArrayList<Tarjetas> getListaTarjetas() {
        return listaTarjetas;
    }
   
   public void reseteoCampos(){
    
    nombreTarjeta.setText("");
    numeroTarjeta.setText("");
    fechaExp.setText("");
    correo.setText("");
}
   
   public int obtenerPosicion(String num){
    for(int i = 0; i < listaTarjetas.size(); i++){
        Tarjetas t = listaTarjetas.get(i);
                if(num.equalsIgnoreCase(t.getNumeroTarjeta())){
                    return i;
    }
    }
    return -1;
   }
   
   public String ocultarNumeros(String num){
    String ocultado = "XXXX-XXXX-XXXX-"; 

    String ultimosCuatro = num.substring(num.length() - 4); 
    String tarjetaOculta = ocultado + ultimosCuatro; 
    return tarjetaOculta;
   }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField correo;
    private javax.swing.JLabel correolabel;
    private javax.swing.JButton editar;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField fechaExp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrar;
    private javax.swing.JTextField nombreTarjeta;
    private javax.swing.JTextField numeroTarjeta;
    private javax.swing.JLabel numerolabel;
    private javax.swing.JTextPane txtTarjetas;
    // End of variables declaration//GEN-END:variables
}
