/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import java.awt.BorderLayout;

/**
 *
 * @author Gerardo
 */
public class usuario extends javax.swing.JPanel {

    /**
     * Creates new form usuario
     */
    public usuario() {
        initComponents();
    }
    registro reg = new registro();
    tarjeta tar =  new tarjeta();
    //ventana ven = new ventana();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase = new javax.swing.JPanel();
        editarPerfil = new javax.swing.JButton();
        agregarTarjeta = new javax.swing.JButton();

        setBackground(new java.awt.Color(4, 80, 113));

        panelBase.setBackground(new java.awt.Color(4, 80, 113));

        editarPerfil.setText("Editar perfil");
        editarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPerfilActionPerformed(evt);
            }
        });

        agregarTarjeta.setText("Agregar Tarjeta");
        agregarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarTarjetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBaseLayout = new javax.swing.GroupLayout(panelBase);
        panelBase.setLayout(panelBaseLayout);
        panelBaseLayout.setHorizontalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaseLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(agregarTarjeta)
                .addGap(161, 161, 161)
                .addComponent(editarPerfil)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        panelBaseLayout.setVerticalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaseLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarTarjeta)
                    .addComponent(editarPerfil))
                .addContainerGap(297, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPerfilActionPerformed
        cambiarPanel(reg);
    }//GEN-LAST:event_editarPerfilActionPerformed

    private void agregarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarTarjetaActionPerformed
        cambiarPanel(tar);

    }//GEN-LAST:event_agregarTarjetaActionPerformed

private void cambiarPanel(javax.swing.JPanel miPanel){
        miPanel.setSize(805,500);
        miPanel.setLocation(0,0);
        panelBase.removeAll();
        panelBase.add(miPanel, BorderLayout.CENTER);
        panelBase.revalidate();
        panelBase.repaint();   
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarTarjeta;
    private javax.swing.JButton editarPerfil;
    private javax.swing.JPanel panelBase;
    // End of variables declaration//GEN-END:variables
}
